### PR TITLE
Native videojs subtitle support

### PR DESCRIPTION
**Pull request by ttshivers**
Video.js support webvtt subtitles. This patch makes synclounge properly notify that the player can support webvtt subtitles when possible (with the `X-Plex-Client-Profile-Extra` header) as well as adding some basic css styling for the subtitles on the player.

### CODE REVIEW

**Comment by ttshivers** [comment]
Fixed #204 in cases where subtitles can be transcoded to webvtt

**Comment by samcm** [comment]
Woah TIL about that header - i'm 100% sure it wasn't a thing when I wrote the player. Awesome! Thers conflicts on this branch, I'll merge when they're resolved 👌

**Comment by ttshivers** [comment]
The big revelation for me was actually that Plex supported transcoding subtitles to webvtt. Plex's API has very little public documentation and it was a matter of looking at the headers other clients sent back to my server and reverse engineering it that way.

**Comment by ttshivers** [comment]
Going to close this PR since it's not compatible with my shaka player PR, and that PR fixes so many more issues than this.

**Pull request closed without merging**
