### PR TITLE
Stringify authentication's default value

### PR DESCRIPTION
**Pull request by brapifra**
This solves the issue mentioned in https://github.com/Starbix/docker-synclounge/issues/13#issue-601644724

```
ErrorWarningSystemArrayLogin


sh: : unknown operand
Rebuilding Webapp for custom options support. This can take a minute or two.
npm WARN SyncLounge@2.0.0 No repository field.
npm WARN SyncLounge@2.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 11620 packages in 8.946s
found 623 vulnerabilities (159 low, 17 moderate, 447 high)
run `npm audit fix` to fix them, or `npm audit` for details

> SyncLounge@2.0.0 build /opt/synclounge
> node build/build.js

authentication/AUTHENTICATION must be a JSON object. Attempting to convert it for you.
- Unable to parse '[object Object]'
- Please check your syntax. Reverting to default.
- Done.
Production settings {
webroot: '',
webapp_port: '8088',
accessUrl: '',
autoJoin: 'true',
autoJoinServer: 'https://<domain here>.com/slserver',
autoJoinRoom: '',
autoJoinPassword: '',
authentication: '[object Object]',
customServer: '',
servers: '',
serverroot: '/slserver',
server_port: '8089'
}
```

### CODE REVIEW

**Comment by MagicalCodeMonkey** [comment]
Tested this and it doesn't remove the output of that error on  `npm run build` but adds additional processing. 
```
authentication/AUTHENTICATION must be a JSON object. Attempting to convert it for you.
- Done.
authentication/AUTHENTICATION must be a JSON object. Attempting to convert it for you.
- Unable to parse '[object Object]'
- Please check your syntax. Reverting to default.
- Done.
```
Did you see the same when you made the change and ran `npm run build`?

However, the error doesn't matter when building, only if it comes up when running the webapp or server. So, it can be safely ignored when running `npm run build`

**Comment by brapifra** [comment]
Hey! Sorry @MagicalCodeMonkey It should be fixed now.
I've noticed that the file is quite hard to follow. Have you guys thought about refactoring some parts and adding a few tests?
Great project btw! :smile:

**Comment by samcm** [comment]
@brapifra Yeah thats my fault, sorry. A lot of this project was written while I was learning JS haha.  Thanks for the PR!

**Comment by brapifra** [comment]
No worries, it's still a great idea :slightly_smiling_face:

**Pull request merged**
