### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by MagicalCodeMonkey**
This provides an authentication mechanism for users that set up their own SyncLounge.

### Settings

To set this, the following setting and format is used
```json
"authentication": {
    "mechanism": "plex",
    "type": ["server", "user"],
    "authorized": [
      "PLEX_SERVER_MACHINE_ID",
      "PLEX_USER_EMAIL",
      "PLEX_USER_NAME",
    ]
  }
```

- `mechanism` specifies how SyncLounge should authenticate a user. This is mostly for future-proofing to allow other authentication mechanisms to be provided. Defaults to `none`.
- `type` is mechanism dependent. Since `plex` is the only one currently, either or both `server` and `user` can be specified.
  - `server` checks against the plex server machine ID (`PLEX_SERVER_MACHINE_ID`). If the user has access to a server matching any of the IDs in the `authorized` list, they will be granted access.
  - `user` checks against the user's email (`PLEX_USER_EMAIL`) or username (`PLEX_USER_NAME`). If either matches a value in the `authorized` list, they will be granted access.
- `authorized` is a list of information for who is authorized.

### Authentication error/failure

While I didn't spend a lot of time trying to figure it out, I couldn't get the error message in App.vue to show on authentication error. Instead, I made it so that if authentication fails, the "Click Me" button will be replaced with a not authorized message as seen below.
image

### Sign-in changes
The sign-in logic flow is changed as well.
- Move Plex Pin Code retrieval and checking to happen when the popup is made.
  I was running into a bug sporadically where if the tab was open too long, you would have to refresh the page to authenticate. This fixes that by having that code only run when `openPopup` is called.

The following are mostly to help with SSO. If the right conditions are met, then the user will be logged in without having to go through Plex OAuth.
So far, I have only tested this with Organizr, but it works!
- Change `code` to `preAuth` in Vue
- Break out common code to `setAuth`
- Add a check to `checkAuth` to make sure `authentication` is set
- Do a pre-auth check when mounted

### Related

This was built upon PR https://github.com/samcm/synclounge/pull/136, which should be merged before this.

### CODE REVIEW

**Comment by samcm** [comment]
You are a legend 😄

**Comment by samcm** [comment]
Ahh this one has merge conflicts with master now 😢. I can have a look in a few hours if you want 👌

**Comment by MagicalCodeMonkey** [comment]
I thought that might happen 😭 I'll try to take a look soon

**Comment by MagicalCodeMonkey** [comment]
I think that should do it for this but I realized that I need to add code to SettingsHelper for https://github.com/samcm/synclounge/pull/137. So I'll do that in a little while

**Comment by MagicalCodeMonkey** [comment]
Updated the original description/comment on this to include changes made to sign-in flow. See "Sign-in changes" there for full details but this code will fix a small bug (serious edge-case) and to allow users to SSO through at least Organizr.

**Pull request merged**
