### PR TITLE
Major cleanup, Vue CLI, completely static, vuexify, and new vuetify migration

### PR DESCRIPTION
**Pull request by ttshivers**
Major cleanup, Vue CLI, completely static, vuexify, and new vuetify migration, edge sync triggering, direct stream, direct play, native subtitles, chromecast support, (auto) skip intro support. I apologise for the absolutely massive size and scope of the PR.

https://github.com/ttshivers/synclounge

### CODE REVIEW

**Comment by ctindel** [comment]
What do you imagine the timeline will be for merging this PR and getting a build out?  It would be most excellent to have a fix for so many of the open issues.

**Comment by ttshivers** [comment]
I already have builds up for my branch for docker and regular NPM binaries:
https://github.com/ttshivers/synclounge
https://hub.docker.com/r/ttshivers/synclounge
https://www.npmjs.com/package/synclounge

Also, I host an instance for my branch: https://synclounge.ttshivers.com/

As for when it will be merged into this repo, I am unsure.

**Comment by ctindel** [comment]
Outstanding.

If I am understanding your docs right on the docker image, you don't have an nginx tag like starbix/synclounge:nginx.  Do you have a sample nginx config somewhere that is known to work?  I'd love to just throw it in a docker image alongside your docker image.

**Comment by ttshivers** [comment]
Make sure to expose port 8088 on the container.

Sample nginx config
```
My version requires a slightly different nginx config since socket and webapp are combined.

Something like:
map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      '';
}


server {
    listen 80;
    listen [::]:80;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name YOURSERVERNAMEHERE;

    # include your ssl certs and parms, etc

    location / {
        proxy_pass http://containeraddress:8088;
        proxy_http_version 1.1;
        proxy_socket_keepalive on;
        proxy_redirect off;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port $server_port;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Sec-WebSocket-Extensions $http_sec_websocket_extensions;
        proxy_set_header Sec-WebSocket-Key $http_sec_websocket_key;
        proxy_set_header Sec-WebSocket-Version $http_sec_websocket_version;
    }
}
```

**Comment by ctindel** [comment]
OK thanks.  One more question, on the other image I could just mount my settings json file into the image at /opt/synclounge/settings.json but the docs seem to say i'm supposed to do environment variables with your image instead.

Is it still possible to overlay a settings.json file?

How would I do environment variables to override things like servers[0].name, servers[0].location etc?

**Comment by ctindel** [comment]
I guess also i should ask, would it be possible for you to publish a docker image with the built-in nginx like the main repos docker image?  It would make transitioning or switching back and forth super easy.

Thanks for the quick responses!

**Comment by ttshivers** [comment]
My image does configuration a bit differently. You don't need to modify the servers config because it's already set up by default to use the socket server in the container. You only need to edit the server config if you plan on using an external server. The image works out of the box with no additional configuration needed.

The server connection flow is changed in my version so that it just automatically selects the best server.

Also, you can't add the normal synclounge servers to the list because my branch uses different message formats.

**Comment by ctindel** [comment]
But the UI still prompts me to select a local or a custom server, and asks me to fill in the custom server url.  

How do I make it so it defaults to a specific custom server, auto join a specific room, etc?  

How do I tell it to disallow the use of other clients?

In my current setup the users navigate to example.com/slweb and the server runs at example.com/slserver, would this one be different?

**Comment by ctindel** [comment]
I think it was because I was overwriting the settings.json file maybe.  I got rid of that overlay volume and now it seems to startup if i just navigate to example.com/ (instead of the old example.com/slweb).

But I authenticate to plex OK, and yet it shows me "No Plex Servers found. Make sure your server owner has shared libraries with you!"

**Comment by ttshivers** [comment]
Can you join the synclounge discord? I can help with that issue but it's probably not best to do it here.

**Comment by ctindel** [comment]
I joined the discord server, what is your username there?

**Comment by ttshivers** [comment]
Looks like this PR got messed up when I deforked my repo. Moving this over to #227

**Pull request closed without merging**
